spring:
  application:
    name: dubbo-boot-customer
  main:
    allow-bean-definition-overriding: true
server:
  port: 9000
dubbo:
  application:
    name: ${spring.application.name}
  registry:
    protocol: zookeeper
    address: 127.0.0.1:2181
  monitor:
    protocol: registry
