spring:
  application:
    name: zipkin-server
server:
  port: 8700
# 监控配置
management:
  #server:
  # 监控服务页面端口
  #port: 8088
  endpoints:
    web:
      # 默认监控前缀
      #      base-path: /monitor
      exposure:
        # 包含端点
        include: "*"
  # 单个端点设置
  endpoint:
    shutdown:
      enabled: false
  # 解决zipkin server UI报错问题
  metrics:
    web:
      server:
        auto-time-requests: false
info:
  app:
    encoding: UTF-8
    java:
      source: 1.8
      target: 1.8
    head: ${spring.application.name}
    body: Welcome, this is ${spring.application.name} @ ${server.port}
